ERROR    my_log:test_login.py:22 接口{"{'code': 'SUCCESS', 'message': '操作成功', 'traceId': '', 'data': {'user': {'id': 1389, 'employeeId': None, 'nickname': '随机昵称', 'avatar': 'https://msb-edu-prod.oss-cn-beijing.aliyuncs.com/default-headimg.png', 'phone': '16688888888', 'systemId': 0, 'clientId': 0, 'unionId': '', 'tokenExpireTime': '2025-07-07 02:05:25', 'sessionId': '3453ea4aef89514695e9b11fe5379ff2', 'token': None}, 'token': 'eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjQwNzA4ODAwMDAsImlkIjoxMzg5LCJ0aW1lIjoxNzIwMjg5MTI1MzQyfQ.cWWZ5vHbjS9aUu_ilWJzF0IGfsjPWJuTJOzMF_x4vbot-bKnQ_dLmMe92KS9vCoN90rFLSdsDVNxktbvdUoXogP_KlXu05dJbwsNbDDvwA3wa4lmHiurDZaTgERsA5Ie9khbpvwqrAIAQP8hM8655vPGCeW6kLQ_U86VfgRWxgo'}}"}