ERROR    my_log:test_login.py:24 接口{"{'code': 'SUCCESS', 'message': '操作成功', 'traceId': '', 'data': {'user': {'id': 1389, 'employeeId': None, 'nickname': '随机昵称', 'avatar': 'https://msb-edu-prod.oss-cn-beijing.aliyuncs.com/default-headimg.png', 'phone': '16688888888', 'systemId': 0, 'clientId': 0, 'unionId': '', 'tokenExpireTime': '2025-07-08 21:36:20', 'sessionId': 'd27db0fc09f462523d10b27dfd05525d', 'token': None}, 'token': 'eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjQwNzA4ODAwMDAsImlkIjoxMzg5LCJ0aW1lIjoxNzIwNDQ1NzgwNDgwfQ.mKJLj3lQsv4k7oLgLgnBc-kfhvprPu8OmtmT65O3C5NtNI-TTBKbZRFaWxFPxnntypc0idsBi1udUWLEtj7kx8XCz3Epn0VMiew0SUTMlj2jG5o7nGFQDlELgvsMHEPQzPlkissI_iLU9236yR88zHvB3wZ9f8iXOGoncMPtODA'}}"}