ERROR    my_log:test_login.py:24 接口{"{'code': 'SUCCESS', 'message': '操作成功', 'traceId': '', 'data': {'user': {'id': 1389, 'employeeId': None, 'nickname': '随机昵称', 'avatar': 'https://msb-edu-prod.oss-cn-beijing.aliyuncs.com/default-headimg.png', 'phone': '16688888888', 'systemId': 0, 'clientId': 0, 'unionId': '', 'tokenExpireTime': '2025-07-08 21:40:44', 'sessionId': '09a8e7daa41cfb2b36aa68a9e467af65', 'token': None}, 'token': 'eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjQwNzA4ODAwMDAsImlkIjoxMzg5LCJ0aW1lIjoxNzIwNDQ2MDQ0MTA4fQ.XR2tcsCd6xqaxPMvw6JFt0-WHF6tj1yBSVm-nXVqlNca-on2ix5YUI488lJp2oJNx0K1Vj_eS5U1tYGFhD5f46oZ1tiv9EA4qZi2frP6OdX1j7btCdb92l91vT9TOZ7WgTuVL7I0yTCda8govhnrGMQjVBay8-4cX0QpwGERZ6c'}}"}