ERROR    my_log:test_login.py:24 接口{"{'code': 'SUCCESS', 'message': '操作成功', 'traceId': '', 'data': {'user': {'id': 1389, 'employeeId': None, 'nickname': '随机昵称', 'avatar': 'https://msb-edu-prod.oss-cn-beijing.aliyuncs.com/default-headimg.png', 'phone': '16688888888', 'systemId': 0, 'clientId': 0, 'unionId': '', 'tokenExpireTime': '2025-07-08 21:39:12', 'sessionId': 'ba4b7171e1029165ceb5826bef3e223d', 'token': None}, 'token': 'eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjQwNzA4ODAwMDAsImlkIjoxMzg5LCJ0aW1lIjoxNzIwNDQ1OTUyMTgwfQ.CzMpLCGCVY-KPo0wLsKq9r2FqUBCAP-8Q11B2Amc1k3Y0k4ff4UAfJ4SFwmfeFV9waMcHuUz6VMpyEvYCQSXtjmnbsNqOx_m9r8LnN_IXFZ4iRBc0u2swHUxpBa8OLzmXyRr5wh6eRMxjc_EsW1wQVCwT-2DH8k9UYOGrfodpZQ'}}"}