ERROR    my_log:test_login.py:24 接口{"{'code': 'SUCCESS', 'message': '操作成功', 'traceId': '', 'data': {'user': {'id': 1389, 'employeeId': None, 'nickname': '随机昵称', 'avatar': 'https://msb-edu-prod.oss-cn-beijing.aliyuncs.com/default-headimg.png', 'phone': '16688888888', 'systemId': 0, 'clientId': 0, 'unionId': '', 'tokenExpireTime': '2025-07-08 21:41:49', 'sessionId': '9b3b60c1f0342ea8342871419421bca7', 'token': None}, 'token': 'eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjQwNzA4ODAwMDAsImlkIjoxMzg5LCJ0aW1lIjoxNzIwNDQ2MTA5OTc1fQ.YEdpHkXYP-1b5pzEOk3cVqgl1LR_o-epI1x73Ckn2-0VCeVFutxHW_4YQngHoRBRpRaAkK1OyCR6DzW-ReTgClfU0puWuKLTaOe4hoIx1192l6EJz7x7sqoA3h3MqdQCUfaVypP6UtEkkb1sFomRFK6cYF6wkou8t3FCImJVllY'}}"}