ERROR    my_log:test_login.py:24 接口{"{'code': 'SUCCESS', 'message': '操作成功', 'traceId': '', 'data': {'user': {'id': 1389, 'employeeId': None, 'nickname': '随机昵称', 'avatar': 'https://msb-edu-prod.oss-cn-beijing.aliyuncs.com/default-headimg.png', 'phone': '16688888888', 'systemId': 0, 'clientId': 0, 'unionId': '', 'tokenExpireTime': '2025-07-17 00:46:54', 'sessionId': '9ec374f8010d54c4cb7ad71c38d63c3e', 'token': None}, 'token': 'eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjQwNzA4ODAwMDAsImlkIjoxMzg5LCJ0aW1lIjoxNzIxMTQ4NDE0MDI5fQ.YbjmRfRmZXC-yFyG8alL7r4d2KchnGEpB8gDxPb_cdhz5e7r38EPyAYkRHY6gFMUPJSaRLHg4STsSEB9q5DIUZPJLs6rOLthE49pZ8spPWRbw11_zDx5IGZdpN6ZqiGZc7pQFkRbuhi90wJGkuVRTdflnZqrDZKK6UoXG_KOyYI'}}"}