ERROR    my_log:test_login.py:22 接口{"{'code': 'SUCCESS', 'message': '操作成功', 'traceId': '', 'data': {'user': {'id': 1389, 'employeeId': None, 'nickname': '随机昵称', 'avatar': 'https://msb-edu-prod.oss-cn-beijing.aliyuncs.com/default-headimg.png', 'phone': '16688888888', 'systemId': 0, 'clientId': 0, 'unionId': '', 'tokenExpireTime': '2025-07-07 02:06:11', 'sessionId': 'bdc55b0debc9da12770814647f27b1dc', 'token': None}, 'token': 'eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjQwNzA4ODAwMDAsImlkIjoxMzg5LCJ0aW1lIjoxNzIwMjg5MTcxNDM0fQ.VYFeY6NEWuBtOlOM4HBu1hYLFQQRNeROhhe7pphsy8geLSO1sgnHsep6vuFIYTuhvrn4qu65Q40eOS4l4hn_6CifzX6a9kizZXbE_-P-faQHAVANUmIcYtscGadeufH1huH7rL-qfA93V74LaK_QKipwzQWsRot9HdpGfFhr0DI'}}"}